# Rustfmt configuration for RolyPoly project
# Official documentation: https://rust-lang.github.io/rustfmt/

# Basic formatting options
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import organization
reorder_imports = true

# Code style
fn_call_width = 80
array_width = 80
chain_width = 80
single_line_if_else_max_width = 50

# Misc
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true

# Note: Many advanced features require nightly rustfmt
# To use them, install nightly and uncomment these lines:
# unstable_features = true
# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"
# trailing_comma = "Vertical"
# trailing_semicolon = true
# format_code_in_doc_comments = true
# normalize_comments = true
