name: GUI

on:
  push:
    branches: [ main ]
    paths:
      - 'gui/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'gui/**'

permissions:
  contents: read

jobs:
  flutter-analyze-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        working-directory: gui
        run: flutter pub get
      - name: Format check
        working-directory: gui
        run: dart format --set-exit-if-changed .
      - name: Analyze
        working-directory: gui
        run: flutter analyze
      - name: Run tests
        working-directory: gui
        run: flutter test
