name: Quality

on:
  push:
    branches: [ main, "release/**", "prerelease/**" ]
  pull_request:
    branches: [ main, "release/**", "prerelease/**" ]

permissions:
  contents: read

jobs:
  rust:
    name: Rust Lint/Test/Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Install tools
        run: |
          cargo install cargo-deny cargo-audit taplo-cli || true

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-0000-0000 || true

      - name: License/ban check
        run: cargo deny check

      - name: TOML format
        run: taplo fmt --check

      - name: Run tests
        run: cargo test --all

  flutter:
    name: Flutter Analyze/Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get deps
        working-directory: gui
        run: flutter pub get
      - name: Format check
        working-directory: gui
        run: dart format --set-exit-if-changed .
      - name: Analyze
        working-directory: gui
        run: flutter analyze
      - name: Tests (with coverage)
        working-directory: gui
        run: flutter test --coverage
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: flutter-coverage
          path: gui/coverage/lcov.info

